services:
  db:
    image: mongo:8.0.3
    restart: unless-stopped
    volumes:
      - db-data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  server:
    build:
      context: .
    environment:
      DB_URL: mongodb://root:example@db:27017/?authSource=admin
      NODE_ENV: production
    ports:
      - 3000:3000

volumes:
  db-data:
