services:
  db:
    image: mongo:8.0.3
    restart: unless-stopped
    volumes:
      - db-data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: myS3cureP4ssword!
  queue:
    image: redis/redis-stack-server:latest
    restart: unless-stopped
    volumes:
      - queue-data:/data/queue
    ports:
      - 6379:6379

volumes:
  db-data:
  queue-data:
