services:
  db:
    image: mongo:8.0.3
    restart: unless-stopped
    volumes:
      - db-data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: myS3cureP4ssword!

volumes:
  db-data:
